title: FreeData - Wir reißen die Linien neu ins Spielfeld.
description: Genossenschaft für digitale Souveränität. Eigentum statt Abhängigkeit. Planbar. Sicher. Gemeinsam.
theme: null
plugins: []
markdown: kramdown
