title: FreeData - Wir ziehen die Linien neu ins Spielfeld.
description: Genossenschaft f체r digitale Souver채nit채t. Eigentum statt Abh채ngigkeit. Planbar. Sicher. Gemeinsam.
theme: null
plugins:
  - jekyll-paginate
markdown: kramdown
excerpt_separator: "<!--more-->"
paginate: 12
paginate_path: "/blog/page:num/"