title: FreeData - Wir ziehen die Linien neu ins Spielfeld.
description: Genossenschaft f체r digitale Souver채nit채t. Eigentum statt Abh채ngigkeit. Planbar. Sicher. Gemeinsam.

url: "https://www.freedata.net"  

theme: minima
markdown: kramdown

minima:
  skin: classic
  include_css:
    - /assets/css/custom.css

plugins:
  - jekyll-paginate
  - jekyll-sitemap

excerpt_separator: "<!--more-->"
paginate: 20
paginate_path: "/blog/page:num/"
permalink: /:categories/:title/